#### Explicitly state the modern kernel driver
driver=nl80211

#### Your actual WiFi interface name
interface={{WIFI_INTERFACE}}

#### The bridge interface name
bridge=br0

#### Your desired WiFi network name
ssid={{WIFI_SSID}}

#### Wireless mode (g for 2.4GHz)
hw_mode=g

#### Ensure explicit multicast-to-unicast mapping is off if your driver struggles
ap_isolate=0

#### Use a strong WiFi password
wpa_passphrase={{WIFI_PASSPHRASE}}

#### WiFi channel
channel=6
wmm_enabled=1
macaddr_acl=0
auth_algs=1
ignore_broadcast_ssid=0
wpa=2
wpa_key_mgmt=WPA-PSK
rsn_pairwise=CCMP
