# Listen only on the IoT LAN bridge interface
interface=br0

# Define the DHCP range for your IoT LAN
# Assign IPs from .100 to .200 for 12 hours
dhcp-range=192.168.10.100,192.168.10.200,12h

# Specify the gateway for DHCP clients (the NanoPi's IP on br0)
dhcp-option=3,192.168.10.1

# Specify DNS servers for DHCP clients
dhcp-option=6,9.9.9.9,1.1.1.1

# --- DHCP Reservations for Fixed IPs ---
# MAC address,Name,IP Adress
# Reserved IP for [[Energy Concierge]] etc. (04-09)
dhcp-host=ec:71:db:e0:9f:b6,horty1.local,192.168.10.4


# Example for a Solar Inverter/s (10-19)
# dhcp-host=AA:BB:CC:DD:EE:F1,solar_inverter1,192.168.10.10

# Example for an EV Charger
# dhcp-host=AA:BB:CC:DD:EE:F2,ev_charger1,192.168.10.20

# Example for a Heat Pump
# dhcp-host=AA:BB:CC:DD:EE:F3,heatpump1,192.168.10.30

# Example for a Home Assistant instance (40-49)
# dhcp-host=AA:BB:CC:DD:EE:F4,heatpump1,192.168.10.40

# Example for a Smart Home devices (50-59)
# dhcp-host=AA:BB:CC:DD:EE:F5,heatpump1,192.168.10.50

# Example for Security Cameras (60-69)
# dhcp-host=AA:BB:CC:DD:EE:F6,heatpump1,192.168.10.60
